services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DOCKER_ENV=true  # Флаг, что мы в Docker
      - DB_HOST=db       # Переопределяем хост
    env_file:
    - .env       # Базовые переменные
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: